### ISSUE TITLE
Small bug in new hotkey -A feature

### ISSUE THREAD

**Issue by steve6375** [chenall/grubutils#1]
hotkey -A
Default 0
title  Amenu1
boot
title Amenu2
boot

When menu loads, first line  Amenu1 is highlighted
User presses a
_selection does NOT move_
User presses a again
selection moves to Amenu2

**Comment by chenall** [comment]
hotkey updated,need  the latest version of grub4dos

**Comment by steve6375** [comment]
Thanks! hotkey 2015-04-08 fixes it.
